name: Deploy Backend (main)

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (IAM user keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get runner public IP
        id: ip
        run: echo "ip=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT

      - name: Authorize runner IP for SSH
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id "${{ secrets.EC2_SECURITY_GROUP_ID }}" \
            --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${{ steps.ip.outputs.ip }}/32,Description='GitHub Actions runner'}]" \
          || echo "Ingress rule already exists"

      - name: Create release archive
        run: git archive --format=tar.gz -o release.tgz HEAD

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "release.tgz"
          target: "/home/${{ secrets.EC2_USER }}/"
          overwrite: true

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            APP_DIR="/home/${USER}/totle-backend"
            RELEASE="/home/${USER}/release.tgz"

            mkdir -p "$APP_DIR"
            tar -xzf "$RELEASE" -C "$APP_DIR"
            rm -f "$RELEASE"
            cd "$APP_DIR"

            corepack enable || true
            if ! command -v pnpm >/dev/null; then
              npm i -g pnpm@9
            fi

            pnpm install --frozen-lockfile || pnpm install

            if pm2 describe totle-backend >/dev/null 2>&1; then
              pm2 restart totle-backend
            else
              pm2 start "pnpm start" --name totle-backend --time
            fi

            pm2 save

      - name: Revoke runner IP (always run)
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id "${{ secrets.EC2_SECURITY_GROUP_ID }}" \
            --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${{ steps.ip.outputs.ip }}/32}]" \
          || echo "Ingress already removed"
